name:                SimpleWebCache
version:             0.1.0.0
github:              "metarin/SimpleWebCache"
license:             BSD3
author:              "metarin"
maintainer:          "mail@metarin.net"
copyright:           "2023 metarin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/metarin/SimpleWebCache#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- wai
- warp
- wai-app-static
- wai-logger
- bytestring
- case-insensitive
- network-uri
- http-types
- http-client
- http-client-tls
- http-reverse-proxy

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  SimpleWebCache-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - SimpleWebCache

tests:
  SimpleWebCache-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - SimpleWebCache
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
